// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjM3BDIWNqEtaK88ui4Zl6kcuCHhDZxdY',
    appId: '1:821053139929:web:1f18cd34d7fce87de807c8',
    messagingSenderId: '821053139929',
    projectId: 'sistema-sirenes-qa',
    authDomain: 'sistema-sirenes-qa.firebaseapp.com',
    storageBucket: 'sistema-sirenes-qa.firebasestorage.app',
    measurementId: 'G-1PNVZL1C56',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjM3BDIWNqEtaK88ui4Zl6kcuCHhDZxdY',
    appId: '1:821053139929:web:56a2ec46cbb838dae807c8',
    messagingSenderId: '821053139929',
    projectId: 'sistema-sirenes-qa',
    authDomain: 'sistema-sirenes-qa.firebaseapp.com',
    storageBucket: 'sistema-sirenes-qa.firebasestorage.app',
    measurementId: 'G-T7EZQLQX0C',
  );
}
