// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Firebase não tem plugin nativo no Linux. Use Windows para sync na nuvem.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGtqOkw9LZ8_Pf9W_WhQyU-aWZe3TEe8s',
    appId: '1:539202171240:android:1d6fdbe545a86e887f66dd',
    messagingSenderId: '539202171240',
    projectId: 'monitor-sirenv2-6d201',
    databaseURL: 'https://monitor-sirenv2-6d201-default-rtdb.firebaseio.com',
    storageBucket: 'monitor-sirenv2-6d201.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPty7URXLaLyyvqQUSYZOXmreq-Ql__bg',
    appId: '1:539202171240:web:6d1d00134b0e2e777f66dd',
    messagingSenderId: '539202171240',
    projectId: 'monitor-sirenv2-6d201',
    authDomain: 'monitor-sirenv2-6d201.firebaseapp.com',
    databaseURL: 'https://monitor-sirenv2-6d201-default-rtdb.firebaseio.com',
    storageBucket: 'monitor-sirenv2-6d201.firebasestorage.app',
    measurementId: 'G-43Z6PPPV1R',
  );
}
